### ISSUE TITLE
需要翻译哪些内容？

### ISSUE THREAD

**Issue by amadeus711** [vitest-dev/docs-cn#1]
建议用 issue 列一个 tasks，将要翻译的内容拆分成小块，供想翻译的同学认领，同时也防止任务冲突

**Comment by elonehoo** [comment]
感谢您的指点，我现在就来查看有什么地方未翻译！

**Comment by baboon-king** [comment]
@elonehoo 
不过，他官方仓库没有 提供多语言的 口子，这个仓库是从 ，官方仓库单独提取出来，后续方便和 官方仓库的 源文档同步吗？

**Comment by elonehoo** [comment]
还不是很确定是否方便和 官方仓库 进行同步

因为我一开始翻译的时候并没有考虑这么多，只是单纯的想要在自己的学校内部作为推广，在翻译的时候遇到了很多的问题，所以发了一些邮件给 [Anthony Fu](https://github.com/antfu) , 所以不小心这件事情被发现了，由于现在的 Vitest 还不是稳定版本，所以官方团队并不建议现在翻译。

**Comment by elonehoo** [comment]
@baboon-king 
我有一个想法，就是使用 印记中文的机器人 进行原文的拉取然后整合PR，如同 [slidevjs/docs-cn](https://github.com/slidevjs/docs-cn) 一样，但是我发现这个机器人我不会用

**Comment by baboon-king** [comment]
> @baboon-king
> 
> 还不是很确定是否方便和 官方仓库 进行同步
> 
> 因为我一开始翻译的时候并没有考虑这么多，只是单纯的想要在自己的学校内部作为推广，在翻译的时候遇到了很多的问题，所以发了一些邮件给 [Anthony Fu](https://github.com/antfu) , 所以不小心这件事情被发现了，由于现在的 Vitest 还不是稳定版本，所以官方团队并不建议现在翻译。
----
原来如此，既然官方虽然说没有出稳定版，目前看来，在使用层面上后续应该没有大变更。 而文档内容大部分也是对使用层面的说明。

或许直接 fork 整个仓库的方式，可以更便于在官方仓库文档更新后与官方文档的同步。

**Comment by baboon-king** [comment]
> @baboon-king 我有一个想法，就是使用 印记中文的机器人 进行原文的拉取然后整合PR，如同 [slidevjs/docs-cn](https://github.com/slidevjs/docs-cn) 一样，但是我发现这个机器人我不会用

----
当然。 

对于 [slidevjs](https://github.com/slidevjs/docs-cn) 来说，他的文档是一个独立的仓库。这非常方便。
但是现在 vitest 的文档是和源代码在一起。

**Comment by elonehoo** [comment]
这些问题我想后续都会有一个非常完美的结局方案
