### ISSUE TITLE
与官方文档进行同步

### ISSUE THREAD

**Issue by elonehoo** [vitest-dev/docs-cn#14]
今天下午开始我会全力进行同步官方文档的任务，可能到时候会将各位的翻译直接照搬，有一个  commit 的覆盖问题，不知道各位是否在意这个事情？

@BTBMan @alexzhang1030 @ouduidui @baboon-king @jp-liu @zhangzhibang0309

**Comment by ouduidui** [comment]
没问题

**Comment by elonehoo** [comment]
嘿嘿嘿

**Comment by elonehoo** [comment]
我也是头一次干这个

**Comment by alexzhang1030** [comment]
这是被 Vitest 官宣了？

**Comment by jp-liu** [comment]
我也是头一次干

**Comment by elonehoo** [comment]
没有，昨天有一个大哥说，「我手动同步仓库有好多东西都没注意到，可以让我考虑一下使用别的社区的方案，我看了看很好玩，想着试试看」具体 #1

**Comment by elonehoo** [comment]
> 这是被 Vitest 官宣了？

没有，昨天有一个大哥说，「我手动同步仓库有好多东西都没注意到，可以让我考虑一下使用别的社区的方案，我看了看很好玩，想着试试看」具体 https://github.com/elonehoo/cn.vitest.dev/issues/1

**Comment by elonehoo** [comment]
反正我的目标已经达成了。。。

**Comment by elonehoo** [comment]
我们学校有很多同学开始使用测试框架在写代码的时候增加单测了

**Comment by alexzhang1030** [comment]
没事我也是第一个干，可以尝试多个方案

**Comment by elonehoo** [comment]
嘿嘿嘿

**Comment by elonehoo** [comment]
> 关于未来是否会变成官方翻译

我的回答是「无所谓，如果成为了那就是我毕业最好的礼物，没有成为也是我学习英语路上的一个巨大飞跃，按照 『
Anthony Fu』的说法，这个仓库也只是 Vitest 中文文档的一个备选，说不定有很多选择呢，反正我是来学英语，然后去给 [Veui](https://github.com/ecomfe/veui) 做英文文档的，不能在被 [顾轶灵](https://github.com/Justineo) 挑刺儿了！！！ 」

**Comment by ouduidui** [comment]
我也是来学英语的哈哈哈 刚好最近也在学vitest

**Comment by alexzhang1030** [comment]
haha 我也是

**Comment by elonehoo** [comment]
你们的翻译我可是一条一条看过去，然后在思考为什么可以这样，我的翻译是哪里出现了问题

**Comment by alexzhang1030** [comment]
> 你们的翻译我可是一条一条看过去，然后在思考为什么可以这样，我的翻译是哪里出现了问题

就是语句通顺与意思表达是否正确这两方面吧
vitest 官方的文档有的地方描述的也很模糊，我在看 vitest 文档的时候有些地方感觉也很奇怪

**Comment by elonehoo** [comment]
我之前翻译都是用一下他到底是干啥的，然后翻译

**Comment by alexzhang1030** [comment]
> 我之前翻译都是用一下他到底是干啥的，然后翻译

我以后会参考这种方式，目前的我还是以官方的文档为准，如果有什么我想加的我会先去官方文档提一个 pr，合并后再来翻译哈哈

**Comment by elonehoo** [comment]
英语好是真的可以为所欲为啊

**Comment by alexzhang1030** [comment]
别误解了，我的英文超级渣的 😢

**Comment by baboon-king** [comment]
支持

**Comment by BTBMan** [comment]
支持

**Comment by elonehoo** [comment]
@LoTwT
ok，我想我找到目前最佳的办法，clone 官方仓库 docs 文件夹，在将其建立一个新的分支，翻译结束之后进行合并
大家觉得如何

**Comment by ouduidui** [comment]
> @LoTwT ok，我想我找到目前最佳的办法，clone 官方仓库 docs 文件夹，在将其建立一个新的分支，翻译结束之后进行合并 大家觉得如何

可以

**Comment by LoTwT** [comment]
可以

**Comment by alexzhang1030** [comment]
> @LoTwT ok，我想我找到目前最佳的办法，clone 官方仓库 docs 文件夹，在将其建立一个新的分支，翻译结束之后进行合并 大家觉得如何

可以

**Comment by elonehoo** [comment]
失败了

**Comment by elonehoo** [comment]
其实同步之后，还是需要去查看什么地方未翻译的是吗

**Comment by alexzhang1030** [comment]
> 其实同步之后，还是需要去查看什么地方未翻译的是吗
> 
> 

对啊，需要去看

**Comment by elonehoo** [comment]
这不是我想象的样子

**Comment by elonehoo** [comment]
我觉得这样还是在两个文档之间进行比对，并不是直接将尚未翻译的地方直接展示在文档中

**Comment by alexzhang1030** [comment]
还是需要探索出一种方式，不然中文文档与英文文档不同步可能会为使用者造成不便。

**Comment by elonehoo** [comment]
在我刚才的实验之后，发现将「Vitest_dev/vitest/docs」变成一个分支之后，在进行合并，就将之前的翻译覆盖了

**Comment by alexzhang1030** [comment]
由于 vitest 的文档与源码放在一起，我觉得可以同步的事情暂缓，目前由维护者手动进行同步。等等看 vitest 后续的变动或者大家找到更好的方案

**Comment by elonehoo** [comment]
我想我可以去其他社区求求经，看看他们的整一个流程是怎么样的，争取我可以给大家一个完美的体验

**Comment by ryanmoyo** [comment]
嘿，我想也许可以使用 @docschina-bot 来进行同步，可以了解一下

**Comment by elonehoo** [comment]
我一直都有这个打算

最近一直在看 [印记中文](https://github.com/docschina) 但是并没有看到怎么使用这个机器人

**Comment by elonehoo** [comment]
> 嘿，我想也许可以使用 @docschina-bot 来进行同步，可以了解一下

如果有这个机会，还劳烦你们教授一下

**Comment by antfu** [comment]
#24 我已经 Call @QC-L 了 👀

**Comment by QC-L** [comment]
这改动有点大，可能要基于英文的重新调整下

**Comment by watonyweng** [comment]
@elonehoo 让 @QC-L 指导一下我们如何操作吧，你意下如何？

**Comment by elonehoo** [comment]
他好像比较忙，在call一下？

**Comment by watonyweng** [comment]
@elonehoo @QC-L 已经配置好 @docschina-bot 了，不知道怎么操作的

**Comment by elonehoo** [comment]
不是很怕麻烦，能同步就好，人工同步会忽略太多东西了

**Comment by QC-L** [comment]
@elonehoo 邀请下 @docschina-bot 进仓库，给个 write 权限即可

**Comment by watonyweng** [comment]
@elonehoo 估计再忙，稍等一下吧

**Comment by elonehoo** [comment]
不好意思，杭州下雨了....

**Comment by elonehoo** [comment]
回来就淋湿了

**Comment by QC-L** [comment]
@elonehoo 自动同步接入好了，目前会自动同步到 dev 分支下
接下来，需要你把所有的文档同步到 dev 分支下。
建议每篇文档逐行检查，这样可以避免内容遗漏。

等你们把所有的文档迁移好，我再把自动同步迁移到 main 分支下

**Comment by elonehoo** [comment]
好！

**Comment by elonehoo** [comment]
有一个疑问，是翻译sync-doc分支下，还是dev分支的呢

**Comment by QC-L** [comment]
@elonehoo dev 分支。
sync-docs 是个占位分支，用来同步用的

**Comment by elonehoo** [comment]
好！开工了！

**Comment by XieZongChen** [comment]
> 好！开工了！

列一个 task 吧，里面说明需要根据分支对照翻译

**Comment by QC-L** [comment]
@elonehoo 

我看了下你合并的 commit，原文变化了很多，你并没有根据原文进行修改。就直接合并了，建议提交前先提交个 PR，在 Files Change 里看下内容变化，根据内容进行调整。

别着急提交，每篇文章都有可能存在遗漏的内容（忘记删掉/添加/修改等），先对比保证与英文行行对应，这样同步才能保证正确。

举个例子，你看下面这篇你提交的文章，就存在很多不一致的地方（说明原文已经发生了变化）：

<img width="982" alt="image" src="https://user-images.githubusercontent.com/13861040/176818171-0c05a2d3-2231-4fff-af4d-6da87b73a4dc.png">

**Comment by elonehoo** [comment]
啊🤔，还真是，我大致浏览了一下，感觉没啥区别我就直接复制粘贴了

**Comment by watonyweng** [comment]
@elonehoo 要不编写一个同步翻译校对的指南吧，方便大家更好地协作

**Comment by QC-L** [comment]
@watonyweng @elonehoo 还有个要注意的点，就是锚点问题，具体参考 vite 的文档以及 windicss 的文档，现在的锚点是中文的，有时会出现异常情况。并且无法和英文对应

**Comment by elonehoo** [comment]
> @watonyweng @elonehoo 还有个要注意的点，就是锚点问题，具体参考 vite 的文档以及 windicss 的文档，现在的锚点是中文的，有时会出现异常情况。并且无法和英文对应

好！站在前辈的肩膀上来完成

**Comment by elonehoo** [comment]
> @elonehoo 要不编写一个同步翻译校对的指南吧，方便大家更好地协作

我去抄一下

**Comment by watonyweng** [comment]
@QC-L @elonehoo 已经完成同步，参考 #77，感谢 @elonehoo @amadeus711 @justforuse 参与贡献，关于`锚点问题`后续会根据反馈再修正
