### ISSUE TITLE
「翻译须知」讨论

### ISSUE THREAD

**Issue by elonehoo** [vitest-dev/docs-cn#16]
针对 [官方文档](https://vitest.dev/) 中的一些技术单词的翻译讨论

**Comment by elonehoo** [comment]
例如 「Test Suite」翻译为 「测试套件」

**Comment by alexzhang1030** [comment]
「Spy」 应当翻译为 「监测 or 监视」，而非「间谍」
「you」 应当翻译为 「你」

**Comment by elonehoo** [comment]
选择链接时，尽量看看官方是否有中文的文档，而不是直接使用原文的链接

**Comment by amadeus711** [comment]
我认为整体可以参考 [翻译须知](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)，针对一些本项目的特有单词，在这里进行补充

**Comment by LoTwT** [comment]
> 「Spy」 应当翻译为 「监测 or 监视」，而非「间谍」 「you」 应当翻译为 「你」

「Spy」译为「监听」，会不会更好理解一些？

**Comment by LoTwT** [comment]
`mock` 的动词和名词 ( `v.` / `n.` )，大家觉得有必要翻译吗，要翻译的话如何翻译更好？就 `模拟` 吗？

**Comment by elonehoo** [comment]
我觉得叫 `模拟` 已经很好了

**Comment by elonehoo** [comment]
我并不能想到其他更好的翻译

**Comment by alexzhang1030** [comment]
> `mock` 的动词和名词 ( `v.` / `n.` )，大家觉得有必要翻译吗，要翻译的话如何翻译更好？就 `模拟` 吗？

像 `Spy` 或 `mock` 这种类似专有名词是否可以在翻译时加上()，比如翻译 mock 为 `模拟(mock)` 更好一点

**Comment by BTBMan** [comment]
觉得feedback loop应该怎么翻译 反馈环？

**Comment by elonehoo** [comment]
循环反馈？反馈循环？

**Comment by alexzhang1030** [comment]
> 循环反馈？反馈循环？

我认为反馈循环不错，不过还是要看具体语境才能确定需要翻译为什么

**Comment by antfu** [comment]
写了一些 https://github.com/vitest-dev/docs-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5

**Comment by alexzhang1030** [comment]
@antfu 大佬对于 `headless logic/code` 有好的翻译建议吗

**Comment by elonehoo** [comment]
已经手动将所有的文档进行了同步，接下来就是增进翻译和等待大佬的机器人入场了！！！

**Comment by alexzhang1030** [comment]
@elonehoo features.md 中有冲突，需要解决

**Comment by antfu** [comment]
> @antfu 大佬对于 `headless logic/code` 有好的翻译建议吗

Reference 在哪？

**Comment by alexzhang1030** [comment]
> > @antfu 大佬对于 `headless logic/code` 有好的翻译建议吗
> 
> Reference 在哪？

https://vitest.dev/guide/comparisons.html#cypress

**Comment by elonehoo** [comment]
> @elonehoo features.md 中有冲突，需要解决

没有解决吗？我解决了吧

**Comment by alexzhang1030** [comment]
> > @elonehoo features.md 中有冲突，需要解决
> 
> 没有解决吗？我解决了吧

目前我拉下来是存在冲突的，我来解决一下吧

**Comment by elonehoo** [comment]
啊🤔

**Comment by elonehoo** [comment]
我看看

**Comment by elonehoo** [comment]
在拉一次试试看？

**Comment by elonehoo** [comment]
我这边没啥问题啊

**Comment by alexzhang1030** [comment]
![image](https://user-images.githubusercontent.com/49969959/160331799-c83d331c-faad-43dd-8d7b-1f15d0ae999a.png)
在最新代码中发现这个，没事我要提 pr 了

**Comment by elonehoo** [comment]
好的！

**Comment by elonehoo** [comment]
我vscode里面是好的

**Comment by elonehoo** [comment]
好尴尬

**Comment by antfu** [comment]
> headless logic/code

非浏览器逻辑

**Comment by alexzhang1030** [comment]
> 非浏览器逻辑

好的！

**Comment by elonehoo** [comment]
# 翻译词讨论

> 原文
> This assertion checks if a value satisfies a certain predicate.

> 目前翻译
> 这个断言检查一个值是否满足某个条件。

将 `predicate` 翻译成 `条件`，打开是否有更好的翻译？

**Comment by daiwanxing** [comment]
提一个小建议，当文档内的自定义容器没有指定 `title` 时，对默认的 type 翻译进行约定。

在 Vitepress 中，自定义容器的 type 有 ：
- `info`
- `warning`
- `tip`
- `danger`
- `details`

目前中文文档对于这些 type 的翻译没有相关约束，例如部分内容将 `tip` 既翻译成了 `提示` 也有翻译 `提醒`，又或者将 `warning` 既翻译成了 `注意` 也有翻译成了 `警告`。

建议统一 type 的翻译，使其更符合读者的阅读习惯和理解。

以下是我的约束建议：

- `info` 说明
- `warning`  注意
- `tip`  提示
- `danger` 警告
- `details` 详情

最后，我想阐述我个人对 `info` 翻译成`说明`的两点原因。

1. `info` 直译成`信息`有点过于苍白，而且`信息`一词在中文中有多种含义，并不一定能准确地表达 info 容器的作用和用途
2.  `说明`一词可以更加准确地表达解释、阐述、澄清的含义，更符合 info 容器用于展示信息和说明的目的

以上，🫡

**Comment by elonehoo** [comment]
好的，感谢，我下班了把它们都改掉

**Comment by elonehoo** [comment]
有了新的 #391 ，故而关闭此讨论，有任何不妥可以开一个新的 issue 进行讨论
