### ISSUE TITLE
迁移到 Vitest 组织

### ISSUE THREAD

**Issue by antfu** [vitest-dev/docs-cn#24]
非常感谢各位的翻译与同步工作！鉴于 Vitest 的 API 已经相对稳定，我认为现在是时候可以把该翻译项目官方化了！

@elonehoo 已邀请你到 GitHub Org，如果你愿意的话可以将仓库进行迁移，迁移后我会配置好权限和部署流程。你也可以加我的 Discord `antfu#3212` 进行沟通。

@QC-L 有空的时候麻烦你看一下能不能给这个仓库配置和主仓库的同步

感谢！

**Comment by alexzhang1030** [comment]
太棒了！

**Comment by elonehoo** [comment]
大哥说了算！

**Comment by elonehoo** [comment]
谢谢这份礼物，真的很棒

**Comment by ryanmoyo** [comment]
wow，我刚想问一下 @QC-L

**Comment by ouduidui** [comment]
wow，太棒了

**Comment by antfu** [comment]
新域名已上线 https://cn.vitest.dev/ 

@elonehoo 麻烦把之前的 cn-vitest 的 Netlify 项目删掉，我来配置 Redirect (好了 ping 我一下）

**Comment by alexzhang1030** [comment]
@antfu 话说有没有考虑将 docs 单独拆出来

**Comment by elonehoo** [comment]
> 新域名已上线 https://cn.vitest.dev/ 
> 
> 
> 
> @elonehoo 麻烦把之前的 cn-vitest 的 Netlify 项目删掉，我来配置 Redirect (好了 ping 我一下）

删掉了🎉

**Comment by antfu** [comment]
> 话说有没有考虑将 docs 单独拆出来

暂时没有，代码和文档在一起有助于保证功能和文档的同步。印记的机器人可以处理这种情况

**Comment by antfu** [comment]
迁移完成。谢谢！

@elonehoo 如果有需要你可以自行邀请仓库协作者。

**Comment by elonehoo** [comment]
呜呼

**Comment by QC-L** [comment]
我来处理下~
