### ISSUE TITLE
翻译任务清单

### ISSUE THREAD

**Issue by elonehoo** [vitest-dev/docs-cn#3]
由于是提取出来的文档，所以可能需要各位同学先去 [官方仓库](https://github.com/vitest-dev/vitest) 看一下是否同步，不同步在进行翻译的工作。目前工作量可能比较大，实在不好意思，我在思考解决的方案了，如果各位同学有解决方案也可以告诉我！

十分感谢各位的帮忙！！

**领取方式，在本 issues 下评论即可。**

-  [x] guide
    - [x] index --- [alexzhang1030](https://github.com/alexzhang1030)
    - [x] why --- [__Catalina](https://github.com/zhangzhibang0309)
    - [x] features --- [__Catalina](https://github.com/zhangzhibang0309)
    - [x] mocking --- [XieZongChen](https://github.com/amadeus711)
    - [x] In-source testing --- [John Long](https://github.com/BTBMan)
    - [x] debugging --- [Lo](https://github.com/LoTwT)
    - [x] migration --- [Lo](https://github.com/LoTwT)
- [x] API
    - [x] test --- [Dewey Ou](https://github.com/ouduidui)
    - [x] describe --- [Dewey Ou](https://github.com/ouduidui)
    - [x] expect --- [Dewey Ou](https://github.com/ouduidui)
    - [x] Setup and Teardown --- [XieZongChen](https://github.com/amadeus711)
    - [x] Vi --- [Lo](https://github.com/LoTwT)
    - [x] MockInstance Methods --- [Lo](https://github.com/LoTwT)
    - [x] MockInstance Properties --- [Lo](https://github.com/LoTwT)
- [x] config --- [alexzhang1030](https://github.com/alexzhang1030)

**Comment by BTBMan** [comment]
@elonehoo guide 下缺少 in-source 项

**Comment by elonehoo** [comment]
@BTBMan 疏忽了

**Comment by elonehoo** [comment]
领取任务 ---- In-source testing

**Comment by zhangzhibang0309** [comment]
请问这是已经翻译完成了吗？

**Comment by elonehoo** [comment]
@zhangzhibang0309 并不会翻译完成，因为 Vitest 还处于开发阶段，并没有进入稳定阶段，所以翻译的工作是需要一直完成下去的，因为昨天 大佬 的点赞，所以从一开始的一个人翻译变成了现在可以有很多同学一起翻译的阶段。如果你也想翻译或者觉得翻译的不好要帮助我们改进都可以提出PR！让我们一起学习英语！！

**Comment by zhangzhibang0309** [comment]
> @zhangzhibang0309 并不会翻译完成，因为 Vitest 还处于开发阶段，并没有进入稳定阶段，所以翻译的工作是需要一直完成下去的，因为昨天 大佬 的点赞，所以从一开始的一个人翻译变成了现在可以有很多同学一起翻译的阶段。如果你也想翻译或者觉得翻译的不好要帮助我们改进都可以提出PR！让我们一起学习英语！！

意思是现在已经翻译完了目前的版本，但是因为vitest持续迭代，现在需要有人来去持续维护并且不断优化翻译。
如果我没理解错误的话我想先试试guide - why和features的翻译任务

**Comment by elonehoo** [comment]
差不多是这个意思，还有一个意思 就是我也不知道现在翻译完了吗 可能需要你在翻译的时候检查是否有缺失的部分，这个工作量可能会非常的巨大！十分感谢你

**Comment by zhangzhibang0309** [comment]
ok，十分高兴能为此项目做出贡献！

**Comment by zhangzhibang0309** [comment]
OK，十分高兴能为此项目做成贡献。
不过我是第一次为开源社区做点儿事情，没什么经验，请问是采取pull requests的方式进行吗？

**Comment by elonehoo** [comment]
> OK，十分高兴能为此项目做成贡献。 不过我是第一次为开源社区做点儿事情，没什么经验，请问是采取pull requests的方式进行吗？

yep

**Comment by zhangzhibang0309** [comment]
好的

**Comment by LoTwT** [comment]
可以参考一下 [Vue 文档官方中文翻译](https://github.com/vuejs-translations/docs-zh-cn) 的工作方式，同步的问题可以看下他们的这个 [关于如何进行英文版同步的问题](https://github.com/vuejs-translations/docs-zh-cn/issues/121)。

**Comment by elonehoo** [comment]
> 可以参考一下 [Vue 文档官方中文翻译](https://github.com/vuejs-translations/docs-zh-cn) 的工作方式，同步的问题可以看下他们的这个 [关于如何进行英文版同步的问题](https://github.com/vuejs-translations/docs-zh-cn/issues/121)。

我觉得我看到了一个不错的方案，我决定找一个时间试试看

**Comment by ouduidui** [comment]
现在还有哪里还没翻译的吗，有的话我可以认领一下

**Comment by elonehoo** [comment]
> 现在还有哪里还没翻译的吗，有的话我可以认领一下

后面没有链接的都是没领取的翻译任务。

因为同步的这个是我手动做的，所以可能会有部分没有同步到，而且 Vitest 后续还是会更新的，所以现在可以领取翻译任务，并且在后续进行长期的翻译任务！需要在翻译的时候在额外进行检查的工作。

**Comment by ouduidui** [comment]
> 

哦，是不是我认领了某个部分，就是长期维护这部分的翻译工作对嘛。

那如果文档更新会通知我们吗哈哈哈

**Comment by ouduidui** [comment]
> > 
> 
> 哦，是不是我认领了某个部分，就是长期维护这部分的翻译工作对嘛。
> 
> 那如果文档更新会通知我们吗哈哈哈

哦，是不是我认领了某个部分，就是长期维护这部分的翻译工作对嘛。

那如果文档更新会通知我们吗哈哈哈

**Comment by alexzhang1030** [comment]
config的话我来认领一下吧

**Comment by elonehoo** [comment]
> > > 
> 
> > 
> 
> > 哦，是不是我认领了某个部分，就是长期维护这部分的翻译工作对嘛。
> 
> > 
> 
> > 那如果文档更新会通知我们吗哈哈哈
> 
> 
> 
> 哦，是不是我认领了某个部分，就是长期维护这部分的翻译工作对嘛。
> 
> 
> 
> 那如果文档更新会通知我们吗哈哈哈

尽量每天更新吧

**Comment by elonehoo** [comment]
> config的话我来认领一下吧
> 
> 

十分感谢

**Comment by ouduidui** [comment]
> 
> 尽量每天更新吧

那我认领一下test describe 和 expect叭。头两个比较少，我也一起领了哈哈哈

**Comment by elonehoo** [comment]
> > 
> > 尽量每天更新吧
> 
> 那我认领一下test describe 和 expect叭。头两个比较少，我也一起领了哈哈哈
> 
> 

呜呼，起飞

**Comment by amadeus711** [comment]
认领 mocking、Setup and Teardown

**Comment by elonehoo** [comment]
> 认领 mocking、Setup and Teardown

呜呼

**Comment by zhangzhibang0309** [comment]
我有个疑问，index指的是？是侧边栏的目录吗，我可以顺便更改自己负责模块的侧栏导航名称吗？

**Comment by zhangzhibang0309** [comment]
还有大家觉得您和你在技术文档中用什么比较合适？之前作者翻译的是您 但我感觉你更合适一点

**Comment by alexzhang1030** [comment]
> 还有大家觉得您和你在技术文档中用什么比较合适？之前作者翻译的是您 但我感觉你更合适一点

我认为`你`更好

**Comment by elonehoo** [comment]
哪里的index.md

**Comment by elonehoo** [comment]
我习惯用您，因为输入法的问题，外加人懒

**Comment by zhangzhibang0309** [comment]
上面翻译任务里面的index

**Comment by zhangzhibang0309** [comment]
我是理解为导航

**Comment by LoTwT** [comment]
认领 debugging、migration、Vi。
术语翻译，我觉得可以先参考一下 vue 文档中文翻译的 [翻译须知](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)

**Comment by alexzhang1030** [comment]
`你`会比`您`看起来更加亲切一点，所以我更偏向于`你`

**Comment by elonehoo** [comment]
在「 guide 目录下的 index.md 」

**Comment by alexzhang1030** [comment]
> 认领 debugging、migration、Vi。 术语翻译，我觉得可以先参考一下 vue 文档中文翻译的 [翻译须知](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)

感谢

**Comment by elonehoo** [comment]
> 上面翻译任务里面的index

在「 guide 目录下的 index.md 」

**Comment by zhangzhibang0309** [comment]
> > 上面翻译任务里面的index
> 
> 在「 guide 目录下的 index.md 」

嗷嗷 index指的是这个啊 我理解错了

**Comment by elonehoo** [comment]
> 认领 debugging、migration、Vi。 术语翻译，我觉得可以先参考一下 vue 文档中文翻译的 [翻译须知](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)

🤔，我再去看看，我现在就去开一个 issue 大家讨论一下

**Comment by elonehoo** [comment]
一下子出现了好多曾经都不曾考虑到的事情

**Comment by alexzhang1030** [comment]
感觉 vue 翻译团队好专业的样子
hhh

**Comment by elonehoo** [comment]
> > > 上面翻译任务里面的index
> > 
> > 
> > 在「 guide 目录下的 index.md 」
> 
> 嗷嗷 index指的是这个啊 我理解错了

没多大事情，到时候我去看看怎么模仿一下其他社区的做法

**Comment by elonehoo** [comment]
不行，我先去解决文档同步的问题，我还没自主写过CI呢

**Comment by alexzhang1030** [comment]
@elonehoo 发现了一个好的 wiki 
https://lctt.github.io/wiki/

**Comment by LoTwT** [comment]
认领 MockInstance Methods、MockInstance Properties

**Comment by alexzhang1030** [comment]
认领 guide/index

**Comment by alexzhang1030** [comment]
这个 issue 是否可以关闭了？

**Comment by ouduidui** [comment]
我觉得可以，先把分工名单同步到wiki

**Comment by elonehoo** [comment]
开着？看看到时候有谁忘记了，我挺上去！我现在可是没有事情干的

**Comment by elonehoo** [comment]
🤔，好吧，那我同步到wiki

**Comment by ouduidui** [comment]
哈哈哈相互查缺补漏叭

**Comment by alexzhang1030** [comment]
@elonehoo 闲着？先把中文文档的搜索修复了，现在不能用/滑稽

**Comment by ouduidui** [comment]
#1 这个issue也可以close了

**Comment by elonehoo** [comment]
> #1 这个issue也可以close了

这个，等同步结束就 close 了！因为好像聊过如何同步

**Comment by elonehoo** [comment]
> @elonehoo 闲着？先把中文文档的搜索修复了，现在不能用/滑稽

突然有活了，我去工作了！

**Comment by ouduidui** [comment]
> > @elonehoo 闲着？先把中文文档的搜索修复了，现在不能用/滑稽
> 
> 突然有活了，我去工作了！

哈哈哈哈 这个好像得去配algolia

**Comment by elonehoo** [comment]
对了，我之前搞了版本号，等一会就要删掉了，然后我去 Discord 问问algolia谁来配置

**Comment by elonehoo** [comment]
对了，我之前搞了版本号，等一会就要删掉了，然后我去 Discord 问问algolia谁来配置

**Comment by elonehoo** [comment]
对了，我之前搞了版本号，等一会就要删掉了，然后我去 Discord 问问algolia谁来配置

**Comment by elonehoo** [comment]
对了，我之前搞了版本号，等一会就要删掉了，然后我去 Discord 问问algolia谁来配置

**Comment by elonehoo** [comment]
我 Discord 打不开了，这里问吧！

@antfu algolia谁来配置啊🤔，我上次失败了，要不再给我一个机会？

**Comment by elonehoo** [comment]
嘿。大家有新的内容啦

**Comment by elonehoo** [comment]
嘿嘿嘿

**Comment by elonehoo** [comment]
初步的同步已经完成了！
