### ISSUE TITLE
快速开始中的示例中的链接有误

### ISSUE THREAD

**Issue by Nauxscript** [vitest-dev/docs-cn#44]
这四个的 Github 链接跳转 404 ，以及其在线试用地址点进去报错

![image](https://user-images.githubusercontent.com/13010589/162758101-0034ac62-74b4-461d-be6d-a952a35d85d5.png)

英文文档中貌似已做更改，但是 jest-dom 的链接和示例移除了。

**Comment by elonehoo** [comment]
来，提个PR
